export interface LearningMeta {
  id: string;
  name: string;
  description: string;
  purpose: string;
  reasonUsed: string;
  relatedComponents: string[];
  exampleCode: string;
  accessibility: string;
  docsUrl: string;
}

export const learningMetadata: Record<string, LearningMeta> = {
  button: {
    id: "button",
    name: "Button",
    description: "클릭 가능한 버튼 컴포넌트",
    purpose: "사용자의 동작을 트리거하거나 양식을 제출할 때 사용합니다.",
    reasonUsed: "영화 탐색, 감상 기록 제출 등 주요 사용자 액션을 위해 사용되었습니다.",
    relatedComponents: ["Tooltip", "Icon"],
    exampleCode: "<Button variant=\"default\">클릭하세요</Button>",
    accessibility: "키보드 포커스와 스페이스/엔터 키 입력을 기본 지원합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/button",
  },
  card: {
    id: "card",
    name: "Card",
    description: "콘텐츠를 그룹화하여 보여주는 컨테이너",
    purpose: "관련된 정보들을 시각적으로 묶어서 표현할 때 사용합니다.",
    reasonUsed: "영화의 포스터, 제목, 정보 등을 하나의 블록으로 묶어 보여주기 위해 사용되었습니다.",
    relatedComponents: ["Aspect Ratio", "Badge"],
    exampleCode: "<Card><CardHeader>제목</CardHeader><CardContent>내용</CardContent></Card>",
    accessibility: "적절한 헤딩 태그를 내부에 사용하여 구조를 명확히 해야 합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/card",
  },
  carousel: {
    id: "carousel",
    name: "Carousel",
    description: "콘텐츠를 가로로 스와이프하거나 넘겨보는 슬라이더",
    purpose: "한정된 공간에서 여러 항목을 보여줄 때 사용합니다.",
    reasonUsed: "인기 영화 목록과 같이 여러 개의 영화 카드를 스와이프하여 탐색할 수 있도록 사용되었습니다.",
    relatedComponents: ["Card"],
    exampleCode: "<Carousel><CarouselContent><CarouselItem>1</CarouselItem></CarouselContent></Carousel>",
    accessibility: "이전/다음 버튼에 명확한 aria-label이 필요하며 키보드 탐색을 지원합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/carousel",
  },
  dialog: {
    id: "dialog",
    name: "Dialog",
    description: "현재 화면 위에 뜨는 모달 팝업",
    purpose: "중요한 정보나 사용자 입력을 집중해서 받을 때 사용합니다.",
    reasonUsed: "예고편 영상 재생이나 통합 검색 등 화면 전환 없이 중요한 컨텍스트를 제공하기 위해 사용되었습니다.",
    relatedComponents: ["Button"],
    exampleCode: "<Dialog><DialogTrigger>열기</DialogTrigger><DialogContent>내용</DialogContent></Dialog>",
    accessibility: "열렸을 때 포커스가 다이얼로그 내부로 이동하며 ESC 키로 닫을 수 있어야 합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/dialog",
  },
  tabs: {
    id: "tabs",
    name: "Tabs",
    description: "관련 콘텐츠를 탭으로 전환하여 보여주는 컴포넌트",
    purpose: "섹션을 나누어 한 번에 하나의 콘텐츠만 보여줄 때 사용합니다.",
    reasonUsed: "홈 화면의 장르별 영화나 상세 페이지의 줄거리/출연진/리뷰 전환에 사용되었습니다.",
    relatedComponents: ["Card"],
    exampleCode: "<Tabs defaultValue=\"tab1\"><TabsList><TabsTrigger value=\"tab1\">탭1</TabsTrigger></TabsList><TabsContent value=\"tab1\">내용</TabsContent></Tabs>",
    accessibility: "방향키를 사용하여 탭 간 이동이 가능해야 합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/tabs",
  },
  accordion: {
    id: "accordion",
    name: "Accordion",
    description: "제목을 클릭하면 내용이 펼쳐지거나 접히는 컴포넌트",
    purpose: "긴 설명글이나 자주 묻는 질문(FAQ) 등 상세 내용을 숨겨두었다가 필요할 때 보여주어 화면 공간을 절약합니다.",
    reasonUsed: "홈 화면 하단의 '자주 묻는 질문' 섹션에서 질문 목록을 깔끔하게 보여주기 위해 사용되었습니다.",
    relatedComponents: ["Card"],
    exampleCode: "<Accordion type=\"single\" collapsible>\n  <AccordionItem value=\"item-1\">\n    <AccordionTrigger>질문</AccordionTrigger>\n    <AccordionContent>답변 내용</AccordionContent>\n  </AccordionItem>\n</Accordion>",
    accessibility: "접고 펴는 상태를 스크린 리더가 인지하며 화살표 키로 항목 간 이동이 가능합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/accordion",
  },
  avatar: {
    id: "avatar",
    name: "Avatar",
    description: "사용자나 단체를 나타내는 원형 이미지/이니셜",
    purpose: "프로필 사진이나 아이콘을 시각적으로 통일감 있게 표시할 때 사용합니다.",
    reasonUsed: "헤더 우측에 로그인한 사용자를 표시하기 위해 적용되었습니다.",
    relatedComponents: ["Dropdown Menu"],
    exampleCode: "<Avatar>\n  <AvatarImage src=\"https://github.com/shadcn.png\" />\n  <AvatarFallback>CN</AvatarFallback>\n</Avatar>",
    accessibility: "이미지가 로드되지 않을 때를 대비한 Fallback 텍스트(예: 이니셜)를 제공합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/avatar",
  },
  "alert-dialog": {
    id: "alert-dialog",
    name: "Alert Dialog",
    description: "사용자의 즉각적인 조치가 필요한 중요 경고 모달",
    purpose: "데이터 삭제나 로그아웃처럼 취소할 수 없거나 중요한 액션을 수행하기 전 한 번 더 확인할 때 사용합니다.",
    reasonUsed: "실수로 로그아웃되는 것을 방지하기 위해 사용되었습니다.",
    relatedComponents: ["Dialog", "Button"],
    exampleCode: "<AlertDialog>\n  <AlertDialogTrigger>삭제</AlertDialogTrigger>\n  <AlertDialogContent>\n    <AlertDialogTitle>정말 삭제할까요?</AlertDialogTitle>\n    <AlertDialogAction>네</AlertDialogAction>\n  </AlertDialogContent>\n</AlertDialog>",
    accessibility: "일반 Dialog보다 더 높은 강제로 화면 밖 상호작용을 차단하며, 취소(Cancel)를 명시적으로 제공해야 합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/alert-dialog",
  },
  "dropdown-menu": {
    id: "dropdown-menu",
    name: "Dropdown Menu",
    description: "버튼을 클릭하면 아래로 펼쳐지는 메뉴 목록",
    purpose: "여러 개의 액션(설정, 로그아웃, 프로필)을 공간 낭비 없이 묶어둘 때 사용합니다.",
    reasonUsed: "헤더의 아바타를 클릭했을 때 나오는 프로필 메뉴 및 로그아웃 버튼을 구성하기 위해 사용되었습니다.",
    relatedComponents: ["Avatar", "Button"],
    exampleCode: "<DropdownMenu>\n  <DropdownMenuTrigger>메뉴</DropdownMenuTrigger>\n  <DropdownMenuContent>\n    <DropdownMenuItem>설정</DropdownMenuItem>\n    <DropdownMenuItem>로그아웃</DropdownMenuItem>\n  </DropdownMenuContent>\n</DropdownMenu>",
    accessibility: "Esc 키로 메뉴를 닫을 수 있고, 화살표 키로 항목 간 위아래 이동이 가능합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/dropdown-menu",
  },
  progress: {
    id: "progress",
    name: "Progress",
    description: "현재 작업의 진행 상태나 채워진 정도를 보여주는 막대",
    purpose: "파일 업로드 상태를 보여주거나, 게임/학습의 완료 퍼센트를 시각화할 때 사용합니다.",
    reasonUsed: "학습 모드에서 사용자가 얼마나 많은 컴포넌트를 확인했는지 달성률을 보여주기 위해 사용되었습니다.",
    relatedComponents: ["Card"],
    exampleCode: "<Progress value={33} className=\"w-[60%]\" />",
    accessibility: "aria-valuenow와 aria-valuemax 속성을 통해 현재 진행률을 스크린 리더에 전달합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/progress",
  },
  breadcrumb: {
    id: "breadcrumb",
    name: "Breadcrumb",
    description: "현재 페이지의 위치를 계층 구조로 보여주는 내비게이션",
    purpose: "사용자가 웹사이트 내 어디에 있는지 파악하고, 상위 페이지로 쉽게 돌아갈 수 있게 합니다.",
    reasonUsed: "영화 상세 페이지에서 '홈 > 탐색 > (현재영화)' 형태로 위치를 표시하기 위해 사용되었습니다.",
    relatedComponents: ["Dropdown Menu"],
    exampleCode: "<Breadcrumb>\n  <BreadcrumbItem>\n    <BreadcrumbLink href=\"/\">Home</BreadcrumbLink>\n  </BreadcrumbItem>\n  <BreadcrumbSeparator />\n  <BreadcrumbItem>\n    <BreadcrumbPage>Current</BreadcrumbPage>\n  </BreadcrumbItem>\n</Breadcrumb>",
    accessibility: "nav 태그와 aria-label='breadcrumb'을 사용하여 내비게이션 요소임을 명시합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/breadcrumb",
  },
  "hover-card": {
    id: "hover-card",
    name: "Hover Card",
    description: "링크나 요소에 마우스를 올리면 추가 정보가 뜨는 카드",
    purpose: "페이지 이동 없이 텍스트나 아이콘의 상세 설명/미리보기를 제공할 때 사용합니다.",
    reasonUsed: "영화 포스터나 제목에 마우스를 올리면 전체 줄거리나 상세 정보를 살짝 엿볼 수 있게 하는 데 사용되었습니다.",
    relatedComponents: ["Tooltip", "Popover"],
    exampleCode: "<HoverCard>\n  <HoverCardTrigger>마우스 오버</HoverCardTrigger>\n  <HoverCardContent>미리보기 상세 정보</HoverCardContent>\n</HoverCard>",
    accessibility: "모바일 등 터치 기기에서는 툴팁처럼 터치 앤 홀드(길게 누르기)로 작동하기도 합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/hover-card",
  },
  "scroll-area": {
    id: "scroll-area",
    name: "Scroll Area",
    description: "커스텀 스크롤바가 적용된 스크롤 가능한 컨테이너",
    purpose: "OS 기본 스크롤바 대신 디자인에 어울리는 얇고 예쁜 스크롤바를 씌우고 싶을 때 사용합니다.",
    reasonUsed: "긴 장르 목록이나 텍스트를 한정된 공간에 표시할 때 디자인 일관성을 위해 사용되었습니다.",
    relatedComponents: ["Separator"],
    exampleCode: "<ScrollArea className=\"h-[200px] w-[350px]\">\n  내용물...\n</ScrollArea>",
    accessibility: "내부 컨텐츠가 스크롤 가능함을 인식하고 마우스 휠 및 키보드로 조작 가능합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/scroll-area",
  },
  tooltip: {
    id: "tooltip",
    name: "Tooltip",
    description: "마우스를 올렸을 때 나타나는 작은 설명 텍스트 창",
    purpose: "아이콘 버튼처럼 텍스트가 없는 요소의 기능을 설명해 줄 때 주로 사용합니다.",
    reasonUsed: "헤더의 검색, 다크모드, 학습 모드 토글 스위치의 기능을 설명하기 위해 사용되었습니다.",
    relatedComponents: ["Hover Card", "Button"],
    exampleCode: "<TooltipProvider>\n  <Tooltip>\n    <TooltipTrigger><Icon/></TooltipTrigger>\n    <TooltipContent>설명 텍스트</TooltipContent>\n  </Tooltip>\n</TooltipProvider>",
    accessibility: "aria-describedby를 통해 버튼의 기능을 스크린 리더 사용자에게 부가적으로 설명합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/tooltip",
  },
  switch: {
    id: "switch",
    name: "Switch",
    description: "설정을 켜거나 끄는 토글 스위치",
    purpose: "사용자가 즉각적으로 상태를 On/Off 해야 하는 환경 설정 옵션에 사용합니다.",
    reasonUsed: "헤더의 '학습 모드'를 켜고 끄는 직관적인 컨트롤을 위해 사용되었습니다.",
    relatedComponents: ["Label", "Checkbox"],
    exampleCode: "<Switch checked={isOn} onCheckedChange={setIsOn} />",
    accessibility: "엔터나 스페이스바로 토글 가능하며 role=\"switch\"로 인식됩니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/switch",
  },
  slider: {
    id: "slider",
    name: "Slider",
    description: "마우스로 드래그하여 숫자 값을 조절하는 슬라이더",
    purpose: "범위 내에서 세밀하게 값을 변경해야 할 때(예: 볼륨, 가격 범위, 평점) 사용합니다.",
    reasonUsed: "영화 탐색 페이지 필터에서 '최소 평점' 조건을 조절할 때 사용되었습니다.",
    relatedComponents: ["Input"],
    exampleCode: "<Slider defaultValue={[33]} max={100} step={1} />",
    accessibility: "키보드 화살표 키, Home/End 키 등을 이용해 값을 조절할 수 있습니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/slider",
  },
  checkbox: {
    id: "checkbox",
    name: "Checkbox",
    description: "여러 옵션 중 하나 이상을 선택하거나 동의할 때 쓰는 체크박스",
    purpose: "필터에서 다중 조건을 선택하거나, 폼에서 약관 동의를 받을 때 사용합니다.",
    reasonUsed: "탐색 페이지 필터에서 '여러 개의 장르'를 중복 선택할 수 있도록 구성할 때 사용되었습니다.",
    relatedComponents: ["Label"],
    exampleCode: "<Checkbox id=\"terms\" />\n<Label htmlFor=\"terms\">동의합니다</Label>",
    accessibility: "체크박스와 Label이 id로 연결되어 있어야 라벨 클릭 시 체크박스가 작동합니다.",
    docsUrl: "https://ui.shadcn.com/docs/components/checkbox",
  },
};
